### ISSUE TITLE
Nastavení editoru na "nano".

### ISSUE THREAD

**Issue by qeef** [webdev-js-evenings/git-workshop#69]
Defaultní editor git lze přenastavit v souboru ~/.gitconfig nasledujicim zpusobem:

[core]
        editor = nano

nebo místo nano cokoli jiného.

**Comment by vojtatranta** [comment]
dík @qeef 
šup pull request!

**Comment by tkapler** [comment]
Já jsem si po minulé session zapsal:
`git config --global core.editor "nano" `
nebo u ubuntu & debianu přes globální nastavení editoru
`sudo update-alternatives --config editor`

**Comment by partyk** [comment]
Já si nastavil Atom a je to funkční pro Windows
`git config --global core.editor atom`

**Comment by qeef** [comment]
Merged, so closed.

**Comment by vojtatranta** [comment]
kdyžtak do pull requestu stačí pak napsat nějaký to `close #69` a zavře se to samo s mergnutym PR.

**Comment by qeef** [comment]
To me zajima. Psals do commit message a v commit message je "Fixes #69" (je jedno, jestli close, fixes, fixed (see https://help.github.com/articles/closing-issues-via-commit-messages/), ale Issue se neuzavrelo...

**Comment by vojtatranta** [comment]
To je otazka, jak to github dela, kdyz to das do pull request description,
tak by to melo jit.

Dne 14. 10. 2016 2:49 odpoledne napsal uživatel "Jiri Hubacek" <
notifications@github.com>:
