### ISSUE TITLE
Nástroje pro deploy

### ISSUE THREAD

**Issue by Nodonisko** [webdev-js-evenings/git-workshop#72]
Bylo by možné ukázat nějaké nástroje pro automatický deploy z GITu?

Třeba když budu chtít aby mi na serveru beželo vždy to co mám v masteru i s nějakým buildem a tak?

**Comment by vojtatranta** [comment]
Heh, na příští přednášce ukážu, jak se dělá bare repozitář, který se dá použít na deploy ale spíše jen na testovací účely. Ale udělá to přesně to, co po mně chceš.

Ten deployment je takový hodně široký téma, protože je k tomu spousta přístupů, jak to dělat.
Přístup přímo přes GIT má hodně nevýhod - na serveru musíš mít celý repozitář - to můžou být gigabyty a je to naprosto zbytečné.

Správně by si měl sever jenom stáhnout nový release a ten si rozbalit popřípadě zmigrovat db nebo tak.

**Comment by Nodonisko** [comment]
Super budu jen rád, když ukážeš jak se to dělá správně, zrovna toto mě hodně zajímá :)

**Comment by vojtatranta** [comment]
Jooo, tys vlastně odešel dřív. Ja to sem doplnim... Snad...

**Comment by vojtatranta** [comment]
Kdyžtak se zeptej Dane Luboše Mátla, ten má dobře vymakanej deployment na KNJ.
