### ISSUE TITLE
Školení

### ISSUE THREAD

**Issue by pavelvtelensky** [webdev-js-evenings/git-workshop#79]
Byl bych rád za nějaké školení, které by vysvětlilo věci z praxe. Nějak tu tápu a nění mě jasné odesílání, synchronizování a práce pokud vytvářím někde na serveru web.

**Comment by vojtatranta** [comment]
Ahoj Pavle,
co myslíš tím "někde na server webu"? Pokud myslis nejaky testovaci deployment, tak to jsem jeste do repozitare nedoplnil - in progress.

**Comment by pavelvtelensky** [comment]
Ahoj, ano myslím to, že máme web, kde mám pro práci testovací doménu neco.domena.cz, na které chci dělat a pracuji tam s gitem a nějak v tom tápu

**Comment by vojtatranta** [comment]
Takže se někam připojíš na vzdálenou plochu a tam pracuješ na vzdáleném serveru?

**Comment by pavelvtelensky** [comment]
připojím se přes terminál SSH pavel@.... mohu ukázat přes TViewer nebo Skype

**Comment by vojtatranta** [comment]
Jo o tom jsme mluvil na školení, že to není úplně fajn přístup.
Jsou tam problemy s pravy s vytezovanim serveru atd. Git je super v tom, ze je decentralizovany a proto je - podle meho nazoru - lepsi, kdyz bezi vyvojiva verze cehokoliv lokalne u vyvojare, ktery pracuje na svem projektu - muze si tam zkouset cokoliv chce a muze pracovat na nekolika verzich najednou nebo nemusi mit svou verzi spustitelnou apod. 

Proto bych nepouzil "pracovni" server ale primo bych do repozitare pridal skripty, ktere rozbehnou cely projket lokalne. Vse je pak snadnejsi a muze se pracovat i offline.

Ale zpatky k otazce.

Pokud jde o to, jak nasadit repozitar na verejny server, tak jsou v zasade dve cesty, jak to udelat.

Prvni cesta je takova, ze proste ze vzdaleneho serveru udelate git server a to proste tak, ze na serveru zavolate git init a pridate post-receive hook (navid dodam do materialu). Pak bude stacit napsat git push a bude vse fungovat nebot git umi pracovat pres ssh. Tohle se nehodi pro produkcni nasazovani, protoze musite na serveru mit celou gitovou hystorii a ta muze mit gigabyty a navic riskujrte, ze se k tomu nekdo z venku dostane a precte si vsechno, co mate v gitu.


Druha cesta je takova, ze zacnete pouzivat nejaky software pro spravu repozitare - bitbucket, github, gitlab a tam se nastavi hooky bapriklad - kdyz oushnu do masteru chci zbuildovat aplikaci do produkcniho modu, zazipovat ji, zaradit ji do releasu a  zavolat nejaky skript treba i na vzdalenem serveru, ktery zazipovanou aplikaci na server stahne a rozbali ji a spusti treba migrave databaze a nastavi web do rezimu udrzby.

**Comment by vojtatranta** [comment]
@pavelvtelensky přidal jsem dolů nastavení, jak si udělat vlastní vzdálený repozitář: https://github.com/webdev-js-evenings/git-workshop/blob/master/advanced.md 

Je to napsáno dole.

**Comment by pavelvtelensky** [comment]
Ahoj děkuji, podívám se
